apiVersion: v1
data:
  haproxy.convert-api.cfg: |
    global
      stats socket /var/run/api.sock user haproxy group haproxy mode 660 level admin expose-fd listeners
      log stdout format raw local0 info

    defaults
      mode http
      log global
      option httplog
      log-format "%ci:%cp -> %si:%sp [%tr] %ST %B bytes to %s"
      option dontlognull
      timeout connect 5s
      timeout client 20s
      timeout server 20s

    frontend http_frontend
      bind *:8080
      default_backend convert-api

    backend convert-api
      balance roundrobin
      option httpchk GET /api/health
      default-server inter 10s fall 3 rise 2
      server convert-api-1 url-shortener-convert-api-1:8080 check
      server convert-api-2 url-shortener-convert-api-2:8080 check
kind: ConfigMap
metadata:
  annotations:
    use-subpath: "true"
  labels:
    io.kompose.service: lb-convert-api
  name: lb-convert-api-cm0
